### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by Nafly09** [Lamarcke/bibliomar-react#1]
Salve mestre, tem alguma feature ou refatoramento que você tem em mente e gostaria que fosse implementados? Afinal de conta o projeto é seu então eu não gostaria de fazer algo que você não tenha interesse. Pode abrir issues e me marcar aqui se tiver alguma em específico que eu tento dar uma olhada assim que sair do horário de serviço.

**Comment by Lamarcke** [comment]
Olá, agradeço em demasiado o interesse.

Sinceramente, estou planejando melhorar um pouco a área de biblioteca no geral, e qualquer ajuda é bem vinda.

Inicialmente, eu gostaria de implementar essas funcionalidades:
- Poder selecionar e mover vários livros de uma só vez, para outra categoria
- Melhorar a interface da biblioteca no geral, já que ela se encontra bem simples.
- Atualmente, seria melhor se o "login automático" que o site tenta fazer ao entrar na biblioteca levasse para uma pagina própria, vazia, e caso ocorresse algum erro redirecionaria para a página de login normal, acho que esse é o mais simples de fazer atualmente.

E uma coisa importante:
As capas de livro não estão ficando corretamente dimensionadas em muitos dispositivos. Atualmente, o site só possui media queries de > 600px e < 600px de viewport nas classes CSS, então em alguns aparelhos elas estão ficando ou muito grandes ou muito esticadas. Seria interessante explorar a opção de `max-width` e `max-height` do CSS, talvez isso já resolva o problema.

E uma mudança no futuro que eu acharia muito interessante seria a opção de instalar o aplicativo direto no navegador, e pra isso ele teria que ser um PWA.

Como o Netlify garante um certificado HTTPS automaticamente, acredito que agora é só questão de configurar tudo certinho.

Aliás, não precisa se acanhar, qualquer mudança que você ou alguém interessado sugerir é muito bem vinda.

**Comment by Lamarcke** [comment]
E também, vinha estudando uma forma de permitir que o usuário leia seus livros online, direto no navegador, e isso seria possível usando essa biblioteca:
https://github.com/gerhardsletten/react-reader

Porém, por mais que tentasse, estava enfrentando um bug descrito no issue #116.

Basicamente, podemos implementar a biblioteca, mas teremos de remover o Strict Mode do react, enquanto lidamos com o desenvolvimento dessa parte do site, mas em um ambiente de produção a biblioteca funciona normalmente.

**Comment by Lamarcke** [comment]
Boa noite, aproveitei a deixa e melhorei um pouco o README, e agora tem um tutorial para iniciantes:
https://github.com/Lamarcke/bibliomar-react/blob/main/IMNEW.md

Fiz alguns issues sobre as coisas que mencionei também.
