### ISSUE TITLE
Mover livros em grupo

### ISSUE THREAD

**Issue by Lamarcke** [Lamarcke/bibliomar-react#2]
Atualmente, no sistema de Biblioteca o usuario pode inserir seus livros em três categorias diferentes, sendo essas:
- Lendo - Livros para leitura imediata
- Planejando ler - Livros para ler na futura
- Backlog - Basicamente, onde você guarda os livros para ler em um futuro distante (ou não)

O nome dessas categorias se encontra diferente no biblioterra, que foi projetado em inglês, por isso é importante manter a documentação do mesmo aberta enquanto trabalha:
[Biblioterra Docs](https://biblioterra.herokuapp.com/v1/docs)

Objetivo: Adicionar funcionalidade de mover vários livros para uma categoria diferente.
Atualmente, você pode trocar a categoria do livro acessando as informações do mesmo e alterando por lá, porém, se você quiser mover vários livros de uma só vez, seria uma tarefa tediosa.

Basicamente, seria interesse ter uma espécie de "modo de edição", onde você seleciona os livros ao clicar neles, e então pode realizar a mudança com um só comando.

Toda essa informação é relevante aos componentes no diretório `src/components/library`.

**Comment by Kaedh** [comment]
Opa boa noite, dahora o projeto!!
Eu fuçando no projeto, não vi nada sobre categoria
pode explicar melhor o que seria essa issue?

**Comment by Lamarcke** [comment]
@Kaedh boa noite, obrigado pelo interesse mano!
Adicionei um pouco mais de descrição, caso você tenha alguma duvida pode comentar aqui.
